<a href="https://colab.research.google.com/github/sury1999/Data-Analysis-Excercises/blob/main/3_NumPy_exercises_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
# your code goes here
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

array([[1, 1],
       [1, 1]])

In [7]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [8]:
# your code goes here
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [10]:
# your code goes here
X = np.arange(4, dtype=np.int)
np.ones_like(X)

array([1, 1, 1, 1])

array([1, 1, 1, 1])

In [11]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [12]:
# your code goes here
X = np.array([[1, 2, 3], [4, 5, 6]], dtype= np.int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [14]:
# your code goes here
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [15]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [16]:
# your code goes here
X = np.array([[2,3], [6,2]], dtype=np.int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

array([[7, 7],
       [7, 7]])

In [17]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [18]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [20]:
# your code goes here
np.random.randint(10, size= [3,3])

array([[0, 7, 3],
       [0, 3, 7],
       [7, 7, 3]])

array([[2, 4, 4],
       [6, 0, 0],
       [8, 3, 2]])

In [21]:
np.random.randint(10, size=3)

array([3, 0, 4])

array([0, 1, 7])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [22]:
# your code goes here
np.random.randn(3,3,3)


array([[[-0.0834871 , -0.80811823,  1.19045918],
        [-0.57530525,  1.1858896 , -0.22512692],
        [ 1.26445756,  0.61353546,  0.15285163]],

       [[-0.50095217, -1.17528021, -0.57189429],
        [-0.0627105 , -0.6261135 ,  1.69241823],
        [ 0.32612981,  1.3138321 ,  0.01406877]],

       [[-1.14498419,  2.00368136, -0.4164143 ],
        [-0.5779139 ,  0.66526807,  2.06555794],
        [ 1.08812227,  0.00663995, -0.23267718]]])

array([[[ 0.29375699,  1.4341624 ,  0.1303376 ],
        [ 0.19469305,  0.33154123, -0.69023195],
        [ 0.37646546,  0.12462134, -0.7681792 ]],

       [[ 1.86267173,  0.29092097, -0.44133214],
        [ 0.86635438,  0.30224057, -0.86920598],
        [-0.03453969, -0.81700075, -0.47043154]],

       [[ 0.014194  ,  0.34409354, -1.15400233],
        [ 1.07144282, -0.81500725, -0.95650017],
        [ 1.11792648, -0.24215313, -1.18875234]]])

In [23]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 1.23770058,  0.04758673, -0.28291022],
        [-0.79843623,  1.5083922 ,  0.50012253],
        [ 0.01647461,  1.30285219, -1.61631756]],

       [[ 3.04833935, -1.08336918, -0.00620284],
        [ 0.01327319, -0.05825154,  0.13241275],
        [-0.67371212,  0.57700852, -0.1818456 ]],

       [[-0.57869669, -0.36859887, -0.65347329],
        [ 0.7010325 ,  0.41688382,  0.81116378],
        [ 0.36239598,  1.30194931,  0.61295809]]])

array([[[ 1.35842405, -0.87464883,  1.16247315],
        [-0.52218733, -0.46802874,  0.77495397],
        [ 0.88905336, -0.7432986 , -2.15331012]],

       [[-0.7652401 , -0.66890287,  1.30162644],
        [ 1.46466524, -0.60558792, -0.6509745 ],
        [-1.03067698,  0.68826651, -0.95246211]],

       [[ 1.51003778, -1.29036557, -1.6952158 ],
        [-1.84498341,  0.06598873,  0.0621233 ],
        [-1.56995645, -0.40403333, -1.12671825]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [24]:
# your code goes here
X = [1,2,3]
Y = np.array(X)
print(Y)

[1 2 3]
[1 2 3]


In [25]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [26]:
# your code goes here
X = np.array([5,2,3], dtype=np.int)
print(X,id(X))
Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 139907930705232
[5 2 3] 139907921829120
[5 2 3] 139907921889600
[5 2 3] 139907922036016


In [27]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 139907921829280
[5 2 3] 139907921828800
[5 2 3] 139907922035696
[5 2 3] 139907921889600


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [28]:
# your code goes here
np.random.randint(10, size=10) + 1

array([ 9,  6,  2,  9,  7, 10,  9,  9,  4,  7])

array([ 1,  8,  7, 10,  9,  5,  7,  6, 10,  9])

In [29]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [30]:
# your code goes here
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [31]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [32]:
# your code goes here
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [34]:
# your code goes here
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [36]:
# your code goes here
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes
800 bytes


In [37]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))
print(Z.size)
print(Z.itemsize)

800 bytes
100
8
800 bytes
100
8


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [38]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[0]

'A'

'A'

In [39]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [40]:
# your code goes here
X[-1]

'E'

'E'

In [41]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [42]:
# your code goes here
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

array(['A', 'B', 'C'], dtype='<U1')

In [43]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [44]:
# your code goes here
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

array(['B', 'C', 'D'], dtype='<U1')

In [45]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [46]:
# your code goes here
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [47]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [48]:
# your code goes here
X[1::2]

array(['B', 'D'], dtype='<U1')

In [49]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [50]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0]

array([1, 2, 3, 4])

In [51]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [52]:
# your code goes here
X[-1]

array([13, 14, 15, 16])

In [53]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [54]:
# your code goes here
X[0, 0]
X[0][0]

1

In [55]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [56]:
# your code goes here
X[-1, -1]

16

In [57]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [58]:
# your code goes here
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [59]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [60]:
# your code goes here
X[:2,:2]

array([[1, 2],
       [5, 6]])

In [61]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [62]:
# your code goes here
X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [63]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [64]:
# your code goes here
X = [-5, -3, 0, 10, 40]
np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

In [65]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [66]:
# your code goes here
X[::-1]

[40, 10, 0, -3, -5]

In [67]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [68]:
# your code goes here
X.sort()
X


[-5, -3, 0, 10, 40]

In [69]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [70]:
# your code goes here
X[4] = 1
X

[-5, -3, 0, 10, 1]

In [71]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [72]:
# your code goes here
X[3] = 40
X

array([ 0.,  0.,  0., 40.,  1.,  0.,  0.,  0.,  0.,  0.])

In [73]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [74]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = np.ones(4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [75]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [76]:
# your code goes here
X[-1:,-1:] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  0]])

In [77]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [78]:
# your code goes here
X += 5

In [79]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [80]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [81]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [82]:
# your code goes here
mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [83]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [84]:
# your code goes here
mask = X > 5
X[mask]

array([ 6, 10])

In [85]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [86]:
# your code goes here
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [87]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [88]:
# your code goes here
mask = (X == 2) | (X==10)
X[mask] 


array([ 2, 10])

In [89]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [90]:
# your code goes here
X.all()

False

In [91]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [92]:
# your code goes here
X.any()

True

In [93]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [94]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

In [95]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [96]:
# your code goes here
X.mean()

4.777777777777778

In [97]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [98]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis = 0)

array([28, 32, 36, 40])

In [99]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [100]:
# your code goes here
X.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

In [101]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [102]:
# your code goes here
X.max()

16

In [103]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10

In [215]:
#to create numpy array: 
[
  [1, 1, 1, 1, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 9, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 1, 1, 1, 1]
]
temp = np.ones((5,5), dtype=int)
temp[1:-1,1:-1] = 0
temp[2,2] = 9
temp
b = temp.copy()
b

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)